services:
  nodebox:
    build:
      context: https://github.com/n04b/nodebox.git
      dockerfile: Dockerfile
    ports:
      - "4343:4343"
    volumes:
      - ./volumes/nodebox/workspace:/workspace
      - ./volumes/nodebox/pm2:/home/node/.pm2